import VerifiedIcon from "@mui/icons-material/Verified";
import LocalOfferIcon from '@mui/icons-material/LocalOffer';
import CancelIcon from '@mui/icons-material/Cancel';
import ShoppingCartIcon from '@mui/icons-material/ShoppingCart';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import OpenInNewIcon from '@mui/icons-material/OpenInNew';
import { FaHandHolding } from 'react-icons/fa';
import { IoLayersSharp } from 'react-icons/io5';
import { GoVerified } from 'react-icons/go';

export const Activity = [
  {
    id: 1,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Sale",
    saleIcon: <ShoppingCartIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 2,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "List",
    // saleIcon: <LocalOfferIcon className="eventTypeIcon" />,
    listIcon: <LocalOfferIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "---",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 3,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "---",
    priceConvert: "",
    quantity: "1",
    eventType: "Minted",
    saleIcon: <AutoAwesomeIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 4,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Offer",
    saleIcon: <FaHandHolding className="eventTypeIcon FaHandHolding" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "---",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 5,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Cancel",
    saleIcon: <CancelIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "---",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 6,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Collection Offer",
    saleIcon: <IoLayersSharp className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "---",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 7,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Sale",
    saleIcon: <ShoppingCartIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    solIcon: "https://i.im.ge/2022/07/15/FohmYF.png",
  },
  {
    id: 8,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "List",
    // saleIcon: <LocalOfferIcon className="eventTypeIcon" />,
    listIcon: <LocalOfferIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "---",
    solIcon: "https://i.im.ge/2022/07/15/FohmYF.png",
  },
  {
    id: 9,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "---",
    priceConvert: "",
    quantity: "1",
    eventType: "Minted",
    saleIcon: <AutoAwesomeIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    solIcon: "https://i.im.ge/2022/07/15/FohmYF.png",
  },
  {
    id: 10,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Offer",
    saleIcon: <FaHandHolding className="eventTypeIcon FaHandHolding" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "---",
    solIcon: "https://i.im.ge/2022/07/15/FohmYF.png",
  },
  {
    id: 11,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Cancel",
    saleIcon: <CancelIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "---",
    solIcon: "https://i.im.ge/2022/07/15/FohmYF.png",
  },
  {
    id: 12,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Collection Offer",
    saleIcon: <IoLayersSharp className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "---",
    solIcon: "https://i.im.ge/2022/07/15/FohmYF.png",
  },
  {
    id: 13,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Sale",
    saleIcon: <ShoppingCartIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 14,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Sale",
    saleIcon: <ShoppingCartIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 15,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Sale",
    saleIcon: <ShoppingCartIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 16,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Sale",
    saleIcon: <ShoppingCartIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 17,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Sale",
    saleIcon: <ShoppingCartIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 18,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Sale",
    saleIcon: <ShoppingCartIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 19,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Sale",
    saleIcon: <ShoppingCartIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
  {
    id: 20,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "Marvelous Degens",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    itemNumber: "350",
    price: "0.03",
    priceConvert: "35.62",
    quantity: "1",
    eventType: "Sale",
    saleIcon: <ShoppingCartIcon className="eventTypeIcon" />,
    time: "2",
    timeIcon: <OpenInNewIcon className="timeIcon" />,
    from: "LutherBlissett_",
    to: "Beach_Monkey",
    ethIcon: "https://i.im.ge/2022/07/15/FohWH1.png",
  },
];
