import VerifiedIcon from "@mui/icons-material/Verified";
import StarOutlineRoundedIcon from '@mui/icons-material/StarOutlineRounded';
import StarRoundedIcon from '@mui/icons-material/StarRounded';

export const solanaTrendingCollections = [
  {
    id: 1,
    coverImg: "https://i.im.ge/2022/07/09/upoen6.jpg",
    avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
    collectionName: "WAGMI United",
    profileName: "",
    desc: "Grifters gonna grift! - powered by Async Blueprints",
    collectionLink: "/collection/grifters-by-xcopy",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 2,
    coverImg: "https://i.im.ge/2022/07/13/ueaDLM.jpg",
    avatar: "https://i.im.ge/2022/07/13/ueaLnD.gif",
    collectionName: "Eternal Dragons: Genesis",
    profileName: "",
    desc: "Grifters gonna grift! - powered by Async Blueprints",
    collectionLink: "/collection/grifters-by-xcopy",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 3,
    coverImg: "https://i.im.ge/2022/07/07/uYiK1G.jpg",
    avatar: "https://i.im.ge/2022/07/07/uYI4FJ.jpg",
    collectionName: "AneroVerse Official",
    profileName: "AneroVerseDeployer",
    desc: "Anero is a decentralized brand without bounds seeking to build a culture, brand and community beyond...",
    collectionLink: "/collection/official-aneroverse",
    profileLink: "/AneroVerseDeployer",
  },
  {
    id: 4,
    coverImg: "https://i.im.ge/2022/07/07/u8WXZq.png",
    avatar: "https://i.im.ge/2022/07/07/u8Z8dy.png",
    collectionName: "Non Either by Rafaël Rozendaal",
    profileName: "ArtBlocks_Admin",
    desc: "Circles move in, circles move out, some light, some dark. 🌹 The work is responsive, it will adapt t...",
    collectionLink: "/collection/non-either-by-rafael-rozendaal",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 5,
    coverImg: "https://i.im.ge/2022/07/07/u8z9p8.png",
    avatar: "https://i.im.ge/2022/07/07/u8HKFM.png",
    collectionName: "NEXUS World - Gen Zero Buddies",
    profileName: "AffynOfficial",
    desc: "“Gen Zero” Buddies are the very first set of NFTs launched by Affyn. There will only ever be 400 Gen...",
    collectionLink: "/collection/nexus-world-gen-zero-buddies",
    profileLink: "/AffynOfficial",
  },
  {
    id: 6,
    coverImg: "https://i.im.ge/2022/07/07/u8JOrJ.png",
    avatar: "https://i.im.ge/2022/07/07/u8nyaF.jpg",
    collectionName: '"MOAR" by Joan Cornella',
    profileName: "TeamFWENCLUB",
    desc: "MOAR by Joan Cornellà is an unusual mansion in the metaverse proudly presented by FWENCLUB, wh...",
    collectionLink: "/collection/official-moar-by-joan-cornella",
    profileLink: "/TeamFWENCLUB",
  },
  {
    id: 7,
    coverImg: "https://i.im.ge/2022/07/07/uR1J00.png",
    avatar: "https://i.im.ge/2022/07/07/uR1GDL.png",
    collectionName: "Subscapes by Matt DesLauriers",
    profileName: "ArtBlocks_Admin",
    desc: "A generative algorithm that draws the impression of a landscape from a multitude of possibilities. T...",
    collectionLink: "/collection/subscapes-by-matt-deslauriers",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 8,
    coverImg: "https://i.im.ge/2022/07/07/uR2y80.png",
    avatar: "https://i.im.ge/2022/07/07/uR2xxL.png",
    collectionName: "Art Blocks Factory",
    profileName: "ArtBlocks_Admin",
    desc: "Art Blocks Factory allows artists who do not wish to wait for approval by the Curation Board a place...",
    collectionLink: "/collection/art-blocks-factory",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 9,
    coverImg: "https://i.im.ge/2022/07/07/uRsjUW.png",
    avatar: "https://i.im.ge/2022/07/07/uRag0m.png",
    collectionName: "ALTAVA Second Skin Metamorphosis",
    profileName: "ALTAVA-Secondskin-Met...",
    desc: "ALTAVA Second Skin : Metamorphosis is your transformed identity in the metaverse inspired by nature ...",
    collectionLink: "/collection/altava-second-skin-metamorphosis",
    profileLink: "/ALTAVA-Secondskin-Metamorphosi",
  },
  {
    id: 10,
    coverImg: "https://i.im.ge/2022/07/07/uRiwPz.png",
    avatar: "https://i.im.ge/2022/07/07/uR08aJ.png",
    collectionName: "ASM AIFA All-Stars",
    profileName: "Altered_State_Machine",
    desc: "40,000 football characters, fast, fun, fully 3D rigged, all-unique and All-Stars!...",
    collectionLink: "/collection/asm-aifa-all-stars",
    profileLink: "/Altered_State_Machine",
  },
  {
    id: 11,
    coverImg: "https://i.im.ge/2022/07/07/uRt1mJ.jpg",
    avatar: "https://i.im.ge/2022/07/07/uRtdXS.jpg",
    collectionName: "Bored Ape Chemistry Club",
    profileName: "YugaLabs",
    desc: "Bored Ape Chemistry Club consists of 10,000 Mutant Serums, to be airdropped to all Bored Apes. Handl...",
    collectionLink: "/collection/bored-ape-chemistry-club",
    profileLink: "/YugaLabs",
  },
  {
    id: 12,
    coverImg: "https://i.im.ge/2022/07/07/uRtLpX.png",
    avatar: "https://i.im.ge/2022/07/07/uRtiwh.png",
    collectionName: "Fermented Fruit by cyberia",
    profileName: "ArtBlocks_Admin",
    desc: "Fermented Fruit is a generative art series designed to live on the Ethereum blockchain and to be ren...",
    collectionLink: "/collection/fermented-fruit-by-cyberia",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 13,
    coverImg: "https://i.im.ge/2022/07/07/uYLaBq.png",
    avatar: "https://i.im.ge/2022/07/07/uYiYir.png",
    collectionName: "Genesis by DCA",
    profileName: "ArtBlocks_Admin",
    desc: "Genesis: Generative System. A block hash string is interpreted into a visual composition using a set...",
    collectionLink: "/collection/genesis-by-dca",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 14,
    coverImg: "https://i.im.ge/2022/07/07/uRtLpX.png",
    avatar: "https://i.im.ge/2022/07/07/uRtiwh.png",
    collectionName: "Fermented Fruit by cyberia",
    profileName: "ArtBlocks_Admin",
    desc: "Fermented Fruit is a generative art series designed to live on the Ethereum blockchain and to be ren...",
    collectionLink: "/collection/fermented-fruit-by-cyberia",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 15,
    coverImg: "https://i.im.ge/2022/07/07/uRtLpX.png",
    avatar: "https://i.im.ge/2022/07/07/uRtiwh.png",
    collectionName: "Fermented Fruit by cyberia",
    profileName: "ArtBlocks_Admin",
    desc: "Fermented Fruit is a generative art series designed to live on the Ethereum blockchain and to be ren...",
    collectionLink: "/collection/fermented-fruit-by-cyberia",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 16,
    coverImg: "https://i.im.ge/2022/07/07/uRtLpX.png",
    avatar: "https://i.im.ge/2022/07/07/uRtiwh.png",
    collectionName: "Fermented Fruit by cyberia",
    profileName: "ArtBlocks_Admin",
    desc: "Fermented Fruit is a generative art series designed to live on the Ethereum blockchain and to be ren...",
    collectionLink: "/collection/fermented-fruit-by-cyberia",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 17,
    coverImg: "https://i.im.ge/2022/07/07/uRtLpX.png",
    avatar: "https://i.im.ge/2022/07/07/uRtiwh.png",
    collectionName: "Fermented Fruit by cyberia",
    profileName: "ArtBlocks_Admin",
    desc: "Fermented Fruit is a generative art series designed to live on the Ethereum blockchain and to be ren...",
    collectionLink: "/collection/fermented-fruit-by-cyberia",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 18,
    coverImg: "https://i.im.ge/2022/07/07/uRtLpX.png",
    avatar: "https://i.im.ge/2022/07/07/uRtiwh.png",
    collectionName: "Fermented Fruit by cyberia",
    profileName: "ArtBlocks_Admin",
    desc: "Fermented Fruit is a generative art series designed to live on the Ethereum blockchain and to be ren...",
    collectionLink: "/collection/fermented-fruit-by-cyberia",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 19,
    coverImg: "https://i.im.ge/2022/07/07/uRtLpX.png",
    avatar: "https://i.im.ge/2022/07/07/uRtiwh.png",
    collectionName: "Fermented Fruit by cyberia",
    profileName: "ArtBlocks_Admin",
    desc: "Fermented Fruit is a generative art series designed to live on the Ethereum blockchain and to be ren...",
    collectionLink: "/collection/fermented-fruit-by-cyberia",
    profileLink: "/ArtBlocks_Admin",
  },
  {
    id: 20,
    coverImg: "https://i.im.ge/2022/07/07/uRtLpX.png",
    avatar: "https://i.im.ge/2022/07/07/uRtiwh.png",
    collectionName: "Fermented Fruit by cyberia",
    profileName: "ArtBlocks_Admin",
    desc: "Fermented Fruit is a generative art series designed to live on the Ethereum blockchain and to be ren...",
    collectionLink: "/collection/fermented-fruit-by-cyberia",
    profileLink: "/ArtBlocks_Admin",
  },
];

export const category = [
  {
    id: 1,
    catImg: "https://i.im.ge/2022/07/09/uHnczM.png",
    label: "All categories",
  },
  {
    id: 3,
    catImg: "https://i.im.ge/2022/07/09/uHnWR4.png",
    label: "Art",
  },
  {
    id: 4,
    catImg: "https://i.im.ge/2022/07/09/uHnBW0.png",
    label: "Collectibles",
  },
  {
    id: 5,
    catImg: "https://i.im.ge/2022/07/09/uHn4jW.png",
    label: "Domain Names",
  },
  {
    id: 6,
    catImg: "https://i.im.ge/2022/07/09/uHnnOr.png",
    label: "Music",
  },
  {
    id: 7,
    catImg: "https://i.im.ge/2022/07/09/uHnf3p.png",
    label: "Photography",
  },
  {
    id: 8,
    catImg: "https://i.im.ge/2022/07/09/uHnvzm.png",
    label: "Sports",
  },
  {
    id: 9,
    catImg: "https://i.im.ge/2022/07/09/uHnHs1.png",
    label: "Trading Cards",
  },
  {
    id: 10,
    catImg: "https://i.im.ge/2022/07/09/uHnk4P.png",
    label: "Utility",
  },
  {
    id: 11,
    catImg: "https://i.im.ge/2022/07/09/uHnptf.png",
    label: "Virtual Worlds",
  },
];

export const time = [
  { label: "last 24 hours", value: "last 24 hours" },
  { label: "last 7 days", value: "last 7 days" },
  { label: "last 30 days", value: "last 30 days" },
  { label: "All time", value: "All time" },
];

export const chainDetails = [
  {
    id: 1,
    chainImg: "https://i.im.ge/2022/07/11/unRw8G.png",
    label: "Ethereum",
  },
  {
    id: 2,
    chainImg: "https://i.im.ge/2022/07/12/u4eWWX.png",
    label: "Polygon",
  },
  {
    id: 3,
    chainImg: "https://i.im.ge/2022/07/12/uBQ224.png",
    label: "Klaytn",
  },
  {
    id: 4,
    chainImg: "https://i.im.ge/2022/07/12/uBQLDm.png",
    label: "Solana",
  },
];

export const TopNfts = [
  {
    id: 1,
    avatar: "https://i.im.ge/2022/07/13/uePFir.png",
    colName: "CryptoPunks",
    volume: "446",
    hour: "+478.86%",
    day: "+404.59%",
    floorPrice: "99.5",
    sale: 50,
    owners: "3.6K",
    items: "10.0K",
    chainName: "ETH",
    ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
    vrifyIcon: <VerifiedIcon className="verify-icon" />,
    watchListIcon: <StarOutlineRoundedIcon className="watchListIcon" />,
    watchListFillIcon: <StarRoundedIcon className="watchListIcon" />,
  },
  // {
  //   id: 2,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   sale: 50,
  //   owners: "3.6K",
  //   items: "10.0K",
  //   chainName: "ETH",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 3,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   sale: 50,
  //   owners: "3.6K",
  //   items: "10.0K",
  //   chainName: "ETH",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 4,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   sale: 50,
  //   owners: "3.6K",
  //   items: "10.0K",
  //   chainName: "ETH",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 5,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   chainName: "ETH",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 6,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   chainName: "ETH",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 7,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   chainName: "ETH",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 8,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   chainName: "ETH",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 9,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   chainName: "ETH",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 10,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   chainName: "ETH",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 11,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 12,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 13,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 14,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 15,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 16,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 17,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 18,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 19,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 20,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 21,
  //   avatar: "https://i.im.ge/2022/07/13/uePFir.png",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 22,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 23,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 24,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 25,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 26,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 27,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 28,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 29,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 30,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 31,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 32,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 33,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 34,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 35,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 36,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 37,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 38,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 39,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
  // {
  //   id: 40,
  //   avatar: "https://i.im.ge/2022/07/09/upXQqF.jpg",
  //   colName: "CryptoPunks",
  //   volume: "446",
  //   hour: "+478.86%",
  //   day: "+404.59%",
  //   floorPrice: "99.5",
  //   owners: "3.6K",
  //   items: "10.0K",
  //   ethIcon: "https://i.im.ge/2022/07/13/ueNHm8.png",
  //   vrifyIcon: <VerifiedIcon className="verify-icon" />,
  // },
];
